// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: order_service_v1/order_service.proto

package order_service_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_order_service_v1_order_service_proto protoreflect.FileDescriptor

const file_order_service_v1_order_service_proto_rawDesc = "" +
	"\n" +
	"$order_service_v1/order_service.proto\x12\x10order_service_v1\x1a-order_service_v1/order_service_messages.proto2\xcf\x01\n" +
	"\fOrderService\x12c\n" +
	"\x0eGetOrderStatus\x12'.order_service_v1.GetOrderStatusRequest\x1a(.order_service_v1.GetOrderStatusResponse\x12Z\n" +
	"\vCreateOrder\x12$.order_service_v1.CreateOrderRequest\x1a%.order_service_v1.CreateOrderResponseB;Z9github.com/ewik2k21/grpcOrderService/pkg/order_service_v1b\x06proto3"

var file_order_service_v1_order_service_proto_goTypes = []any{
	(*GetOrderStatusRequest)(nil),  // 0: order_service_v1.GetOrderStatusRequest
	(*CreateOrderRequest)(nil),     // 1: order_service_v1.CreateOrderRequest
	(*GetOrderStatusResponse)(nil), // 2: order_service_v1.GetOrderStatusResponse
	(*CreateOrderResponse)(nil),    // 3: order_service_v1.CreateOrderResponse
}
var file_order_service_v1_order_service_proto_depIdxs = []int32{
	0, // 0: order_service_v1.OrderService.GetOrderStatus:input_type -> order_service_v1.GetOrderStatusRequest
	1, // 1: order_service_v1.OrderService.CreateOrder:input_type -> order_service_v1.CreateOrderRequest
	2, // 2: order_service_v1.OrderService.GetOrderStatus:output_type -> order_service_v1.GetOrderStatusResponse
	3, // 3: order_service_v1.OrderService.CreateOrder:output_type -> order_service_v1.CreateOrderResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_service_v1_order_service_proto_init() }
func file_order_service_v1_order_service_proto_init() {
	if File_order_service_v1_order_service_proto != nil {
		return
	}
	file_order_service_v1_order_service_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_v1_order_service_proto_rawDesc), len(file_order_service_v1_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_service_v1_order_service_proto_goTypes,
		DependencyIndexes: file_order_service_v1_order_service_proto_depIdxs,
	}.Build()
	File_order_service_v1_order_service_proto = out.File
	file_order_service_v1_order_service_proto_goTypes = nil
	file_order_service_v1_order_service_proto_depIdxs = nil
}
