// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: order_service_v1/order_service_messages.proto

package pkg

import (
	spot_instrument_v1 "github.com/ewik2k21/grpcSpotInstrumentService/pkg/spot_instrument_v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_CREATED    Status = 0
	Status_PROCESSING Status = 1
	Status_PROCESSED  Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "CREATED",
		1: "PROCESSING",
		2: "PROCESSED",
	}
	Status_value = map[string]int32{
		"CREATED":    0,
		"PROCESSING": 1,
		"PROCESSED":  2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_order_service_v1_order_service_messages_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_order_service_v1_order_service_messages_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_order_service_v1_order_service_messages_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_MARKET_ORDER OrderType = 0
	OrderType_LIMIT_ORDER  OrderType = 1
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "MARKET_ORDER",
		1: "LIMIT_ORDER",
	}
	OrderType_value = map[string]int32{
		"MARKET_ORDER": 0,
		"LIMIT_ORDER":  1,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_service_v1_order_service_messages_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_order_service_v1_order_service_messages_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_order_service_v1_order_service_messages_proto_rawDescGZIP(), []int{1}
}

type GetOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusRequest) Reset() {
	*x = GetOrderStatusRequest{}
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusRequest) ProtoMessage() {}

func (x *GetOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_service_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=order_service_v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusResponse) Reset() {
	*x = GetOrderStatusResponse{}
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusResponse) ProtoMessage() {}

func (x *GetOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_service_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderStatusResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_CREATED
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	UserRole      spot_instrument_v1.UserRole `protobuf:"varint,1,opt,name=user_role,json=userRole,proto3,enum=common.UserRole" json:"user_role,omitempty"`
	UserId        string                      `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MarketId      string                      `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	OrderType     OrderType                   `protobuf:"varint,4,opt,name=order_type,json=orderType,proto3,enum=order_service_v1.OrderType" json:"order_type,omitempty"`
	Price         float64                     `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                     `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_service_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetUserRole() spot_instrument_v1.UserRole {
	if x != nil {
		return x.UserRole
	}
	return spot_instrument_v1.UserRole(0)
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_MARKET_ORDER
}

func (x *CreateOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrderRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=order_service_v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_service_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_CREATED
}

type StreamOrderUpdatesRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	UserRole      spot_instrument_v1.UserRole `protobuf:"varint,1,opt,name=user_role,json=userRole,proto3,enum=common.UserRole" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrderUpdatesRequest) Reset() {
	*x = StreamOrderUpdatesRequest{}
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrderUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrderUpdatesRequest) ProtoMessage() {}

func (x *StreamOrderUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrderUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamOrderUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_service_messages_proto_rawDescGZIP(), []int{4}
}

func (x *StreamOrderUpdatesRequest) GetUserRole() spot_instrument_v1.UserRole {
	if x != nil {
		return x.UserRole
	}
	return spot_instrument_v1.UserRole(0)
}

type OrderStatusUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=order_service_v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusUpdateResponse) Reset() {
	*x = OrderStatusUpdateResponse{}
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusUpdateResponse) ProtoMessage() {}

func (x *OrderStatusUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusUpdateResponse.ProtoReflect.Descriptor instead.
func (*OrderStatusUpdateResponse) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_service_messages_proto_rawDescGZIP(), []int{5}
}

func (x *OrderStatusUpdateResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_CREATED
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=order_service_v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_service_messages_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_CREATED
}

type UpdateOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=order_service_v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusResponse) Reset() {
	*x = UpdateOrderStatusResponse{}
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusResponse) ProtoMessage() {}

func (x *UpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_service_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_service_messages_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrderStatusResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_CREATED
}

var File_order_service_v1_order_service_messages_proto protoreflect.FileDescriptor

const file_order_service_v1_order_service_messages_proto_rawDesc = "" +
	"\n" +
	"-order_service_v1/order_service_messages.proto\x12\x10order_service_v1\x1a\x19common/proto/common.proto\"K\n" +
	"\x15GetOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"J\n" +
	"\x16GetOrderStatusResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.order_service_v1.StatusR\x06status\"\xe7\x01\n" +
	"\x12CreateOrderRequest\x12-\n" +
	"\tuser_role\x18\x01 \x01(\x0e2\x10.common.UserRoleR\buserRole\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmarket_id\x18\x03 \x01(\tR\bmarketId\x12:\n" +
	"\n" +
	"order_type\x18\x04 \x01(\x0e2\x1b.order_service_v1.OrderTypeR\torderType\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\"b\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.order_service_v1.StatusR\x06status\"J\n" +
	"\x19StreamOrderUpdatesRequest\x12-\n" +
	"\tuser_role\x18\x01 \x01(\x0e2\x10.common.UserRoleR\buserRole\"M\n" +
	"\x19OrderStatusUpdateResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.order_service_v1.StatusR\x06status\"g\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.order_service_v1.StatusR\x06status\"M\n" +
	"\x19UpdateOrderStatusResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.order_service_v1.StatusR\x06status*4\n" +
	"\x06Status\x12\v\n" +
	"\aCREATED\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\r\n" +
	"\tPROCESSED\x10\x02*.\n" +
	"\tOrderType\x12\x10\n" +
	"\fMARKET_ORDER\x10\x00\x12\x0f\n" +
	"\vLIMIT_ORDER\x10\x01B*Z(github.com/ewik2k21/grpcOrderService/pkgb\x06proto3"

var (
	file_order_service_v1_order_service_messages_proto_rawDescOnce sync.Once
	file_order_service_v1_order_service_messages_proto_rawDescData []byte
)

func file_order_service_v1_order_service_messages_proto_rawDescGZIP() []byte {
	file_order_service_v1_order_service_messages_proto_rawDescOnce.Do(func() {
		file_order_service_v1_order_service_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_service_v1_order_service_messages_proto_rawDesc), len(file_order_service_v1_order_service_messages_proto_rawDesc)))
	})
	return file_order_service_v1_order_service_messages_proto_rawDescData
}

var file_order_service_v1_order_service_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_order_service_v1_order_service_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_order_service_v1_order_service_messages_proto_goTypes = []any{
	(Status)(0),                       // 0: order_service_v1.Status
	(OrderType)(0),                    // 1: order_service_v1.OrderType
	(*GetOrderStatusRequest)(nil),     // 2: order_service_v1.GetOrderStatusRequest
	(*GetOrderStatusResponse)(nil),    // 3: order_service_v1.GetOrderStatusResponse
	(*CreateOrderRequest)(nil),        // 4: order_service_v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),       // 5: order_service_v1.CreateOrderResponse
	(*StreamOrderUpdatesRequest)(nil), // 6: order_service_v1.StreamOrderUpdatesRequest
	(*OrderStatusUpdateResponse)(nil), // 7: order_service_v1.OrderStatusUpdateResponse
	(*UpdateOrderStatusRequest)(nil),  // 8: order_service_v1.UpdateOrderStatusRequest
	(*UpdateOrderStatusResponse)(nil), // 9: order_service_v1.UpdateOrderStatusResponse
	(spot_instrument_v1.UserRole)(0),  // 10: common.UserRole
}
var file_order_service_v1_order_service_messages_proto_depIdxs = []int32{
	0,  // 0: order_service_v1.GetOrderStatusResponse.status:type_name -> order_service_v1.Status
	10, // 1: order_service_v1.CreateOrderRequest.user_role:type_name -> common.UserRole
	1,  // 2: order_service_v1.CreateOrderRequest.order_type:type_name -> order_service_v1.OrderType
	0,  // 3: order_service_v1.CreateOrderResponse.status:type_name -> order_service_v1.Status
	10, // 4: order_service_v1.StreamOrderUpdatesRequest.user_role:type_name -> common.UserRole
	0,  // 5: order_service_v1.OrderStatusUpdateResponse.status:type_name -> order_service_v1.Status
	0,  // 6: order_service_v1.UpdateOrderStatusRequest.status:type_name -> order_service_v1.Status
	0,  // 7: order_service_v1.UpdateOrderStatusResponse.status:type_name -> order_service_v1.Status
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_order_service_v1_order_service_messages_proto_init() }
func file_order_service_v1_order_service_messages_proto_init() {
	if File_order_service_v1_order_service_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_v1_order_service_messages_proto_rawDesc), len(file_order_service_v1_order_service_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_service_v1_order_service_messages_proto_goTypes,
		DependencyIndexes: file_order_service_v1_order_service_messages_proto_depIdxs,
		EnumInfos:         file_order_service_v1_order_service_messages_proto_enumTypes,
		MessageInfos:      file_order_service_v1_order_service_messages_proto_msgTypes,
	}.Build()
	File_order_service_v1_order_service_messages_proto = out.File
	file_order_service_v1_order_service_messages_proto_goTypes = nil
	file_order_service_v1_order_service_messages_proto_depIdxs = nil
}
